
/**
 * @file uplus_config_platform.h
 * @brief
 *
 * @date 2017-01-11
 * @author fanming
 *
 */

#ifndef __UPLUS_CONFIG_PLATFORM_H__
#define __UPLUS_CONFIG_PLATFORM_H__

/*
 * config parameters
*/

#define UPLUS_CONFIG_HW_VER "U_2.0.00"

#define UPLUS_CONFIG_SW_VER "2.7.01"

#define UPLUS_CONFIG_PLATFORM "UDISCOVERY_UWT"

#define UPLUS_CONFIG_MAX_CLIENT_NUM 8

#define UPLUS_CONFIG_CONF_EXTEND_BLOCK_NUM 0

#define UPLUS_CONFIG_MAX_WIFI_SCAN_AP_NUM 32

#define UPLUS_CONFIG_WIFI_CONFIG_SMARTLINK_TIME 1800

#define UPLUS_CONFIG_WIFI_CONFIG_SOFTAP_TIME 1800

#define UPLUS_CONFIG_WIFI_CONFIG_SMARTAP_TIME 1800

#define UPLUS_CONFIG_WIFI_CONFIG_THIRD_TIME 1800

#define UPLUS_CONFIG_WIFI_CONFIG_SMARTLINK_TO_SOFTAP_TIME 60

#define UPLUS_CONFIG_LED_TO_POWER_SAVE_TIME 3600

#define UPLUS_CONFIG_PRODUCT_MODE_WIFI_CONN_TIME 3600

#define UPLUS_CONFIG_WATCHDOG_TIME 60

#define UPLUS_CONFIG_SUPPORT_PRODUCT_MODE 0

#define UPLUS_CONFIG_ENTER_PRODUCT_MODE_POWER_ON_WITHOUT_WIFI_CONF 0

#define UPLUS_CONFIG_SMARTLINK_METHOD_NUM 0

#define UPLUS_CONFIG_SOFTAP_METHOD_NUM 0

#define UPLUS_CONFIG_VERDOR_ID "haier"

#define UPLUS_CONFIG_FAST_WIFI_CONN_INTERVAL 3

#define UPLUS_CONFIG_FAST_WIFI_CONN_TIME 180

#define UPLUS_CONFIG_SLOW_WIFI_CONN_INTERVAL 60

#define UPLUS_CONFIG_SLOW_WIFI_CONN_TIME -1

#define UPLUS_CONFIG_AP_CHANNEL 6

#define UPLUS_CONFIG_SUPPORT_MON_SOFTAP 0

/*
 * module to be included
*/
#define UPLUS_INCLUDE_WIFI_CONN_STA 0

#define UPLUS_INCLUDE_WIFI_CONN_NET 1

#define UPLUS_INCLUDE_SMARTLINK 0

#define UPLUS_INCLUDE_WIFI_CONN_MON 0

#define UPLUS_INCLUDE_SMARTLINK_METHOD_UH 0

#define UPLUS_INCLUDE_SMARTLINK_METHOD_WX 0

#define UPLUS_INCLUDE_SOFTAP 0

#define UPLUS_INCLUDE_WIFI_CONN_AP 0

#define UPLUS_INCLUDE_SOFTAP_METHOD_UH 0

#define UPLUS_INCLUDE_WIFI_SCAN 0

#define UPLUS_INCLUDE_EPP 0

#define UPLUS_INCLUDE_OTA 0

#define UPLUS_INCLUDE_WIFI_LOC 0

#define UPLUS_INCLUDE_PLUGIN 0

#define UPLUS_INCLUDE_MONITOR_REBOOT 0

#endif /*__UPLUS_CONFIG_PLATFORM_H__*/

